name: portifolio_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  velocity_x: ^3.5.1
  #flutter_icons: ^1.1.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.3
  flutter_svg: ^1.1.0
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
